name: Deploy to s3
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
            node-version: 16
            cache: 'npm'
      - name: Build project files
        run: |
          npm ci
          npm install
          npm run build
      - name: Deploy to s3
        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1'
        run: 
          aws s3 cp dist s3://philagov-vue-apps/prisons-daily-census-report/staging --recursive # change it